### ISSUE TITLE
Link to samples and docs redirects to 404

### ISSUE THREAD

**Issue by AlfredoMS** [AzureAD/azure-activedirectory-library-for-dotnet#448] opened 2016-06-08 15:58 UTC
The link to the samples and documentation  in the README.md file redirects to https://github.com/AzureADSamples which returns 404.

**Comment by SaadBinShahid** [comment] 2016-06-21 06:43
Anybody found the correct link ?

**Comment by kpanwar** [comment] 2016-06-22 19:48
duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/452

**Closed by kpanwar** 2016-06-22 19:48 UTC
Labels: Duplicate
