### ISSUE TITLE
Seamless SSO and Azure AD Join

### ISSUE THREAD

**Issue by ghelyar** [AzureAD/azure-activedirectory-library-for-dotnet#1098] opened 2018-06-21 12:50 UTC
I have followed this documentation on Seamless SSO
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/adal-and-seamless-sso
(dead link due to missing http:// on aka.ms by the way)
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)

The code I'm using is:
```
var authContext = new AuthenticationContext("https://login.microsoftonline.com/" + tenantId, new TokenCache());
var authResult = await authContext.AcquireTokenAsync("00000002-0000-0000-c000-000000000000", appId, new UserCredential());
```

This works on an environment using ADFS, or only AD Join, or only Seamless SSO, but fails when using AD Join and Seamless SSO together.

I have tried this on ADAL 3.19.1 and ADAL 3.19.8.

Using logging as described here:
https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Logging-in-ADAL.Net#new-way-of-logging-controlling-pii-adalnet--318

With this logging, I see:
```
LoggerBase.cs:  WS-Trust endpoint 'https://autologon.microsoftazuread-sso.com/<tenantid>/winauth/trust/2005/windowstransport?client-request-id=<guid>' fetched from MEX at 'https://autologon.microsoftazuread-sso.com/<tenantid>/winauth/trust/mex?client-request-id=<guid>'
LoggerBase.cs: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote server returned an error: (401) Unauthorized. ---> System.ComponentModel.Win32Exception: The system cannot contact a domain controller to service the authentication request. Please try again later
   at System.Net.NTAuthentication.GetOutgoingBlob(Byte[] incomingBlob, Boolean throwOnError, SecurityStatus& statusCode)
   at System.Net.NTAuthentication.GetOutgoingBlob(String incomingBlob)
   at System.Net.NegotiateClient.DoAuthenticate(String challenge, WebRequest webRequest, ICredentials credentials, Boolean preAuthenticate)
   at System.Net.NegotiateClient.Authenticate(String challenge, WebRequest webRequest, ICredentials credentials)
   at System.Net.AuthenticationManagerDefault.Authenticate(String challenge, WebRequest request, ICredentials credentials)
   at System.Net.AuthenticationState.AttemptAuthenticate(HttpWebRequest httpWebRequest, ICredentials authInfo)
   at System.Net.HttpWebRequest.CheckResubmitForAuth()
   at System.Net.HttpWebRequest.CheckResubmit(Exception& e, Boolean& disableUpload)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Http.HttpClientWrapper.<GetResponseAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.WsTrust.WsTrustRequest.<SendRequestAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenNonInteractiveHandler.<PreTokenRequest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
```

Additional stack trace in exception, but not in log:
```
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContextIntegratedAuthExtensions.<AcquireTokenAsync>d__0.MoveNext()
```

Is the code wrong, or is there a problem with the environment?

This documentation suggests that this should be a common scenario:
https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-sso

> For Windows 10, the recommendation is to use Azure AD Join for the optimal single sign-on experience with Azure AD.

**Comment by ghelyar** [comment] 2018-07-26 06:44
Is there any update on this? We're seeing it on multiple Azure tenants.

**Comment by jmprieur** [comment] 2018-07-26 12:38
@ghelyar : according to the Seamless SSO PMS, the 401 unauthorized response is expected as part of the happy flow.
This indicates that it’s an environment issue. you need to verify that the device you are using is really domain joined. If the device has problems connecting with the DC (according to the error) – you shouldn’t be able to log into the domain when you starts up the device as well.

Once we’re sure the device is domain joined, we can continue diagnosing the windows auth logs on your machines.  When that's the case please contact me so that I share instructions to collect those logs

**Comment by joshexltd** [comment] 2018-07-31 15:41
@jmprieur The scenario when this exception is thrown is when a machine is joined to Azure Active Directory and Seamless SSO has been set up (using password hash option). You cannot join a machine to an Active Directory domain when the machine is joined to Azure AD. If the machine is Azure AD joined and Seamless SSO is not configured OR the machine is not Azure AD joined and Seamless SSO is configured, I do not get the 
_(401) Unauthorized. ---> System.ComponentModel.Win32Exception: The system cannot contact a domain controller to service the authentication request_ exception. Are you able to share the instructions  to collect windows auth logs at all that could shed some light on this issue? Many Thanks

**Comment by jmprieur** [comment] 2018-07-31 18:18
@joshexltd: the instructions to collect logs are:
1)	Open cmd as an administrator
2)	Run the “startauth.cmd” script (see zip attached)
3)	Go through the authentication when Seamless SSO is turned on – which will still not work
4)	Run the “stopauth.cmd” script
5)	Zip all the log files in the .\logs\ folder (relative to current directory in the command prompt window) and sent it to me (Jean-Marc.Prieur at microsoft.com). I'll forward to the seamless SSO team.

[startauth.zip](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/2246575/startauth.zip)

**Comment by Nadav-N** [comment] 2018-08-02 19:49
According to the windows auth logs that were collected - the problem is not related to Seamless SSO and is only due to client connectivity\configuration.
Basically, the client machine can't find a domain controller to authenticate against.
-	Is the client on a network with a DC?
-	If so, was DNS configured properly so the client could find the DC? The ‘nltest’ command can help with this, particularly ‘nltest /dsgetdc:<domain>’
-	If not, does the customer have a KDC Proxy deployed (and if so, how, because windows doesn’t seem to be picking up the configuration for it)?

**Comment by joshexltd** [comment] 2018-08-08 09:12
The client is not on a network with a DC - it is Azure AD joined - you cannot have a machine that Azure AD joined and joined to Active Directory. In this scenario I do not believe it should be attempting to authenticate with a DC but clearly is as per the error message. Do you have any other thoughts or suggestions at all? Many Thanks

**Comment by jmprieur** [comment] 2018-08-08 11:10
@joshexltd : are you sure that in the latest version of windows 10, you cannot have machine that is both AAD joint and domain joint?

**Comment by joshexltd** [comment] 2018-08-09 10:52
Here the version that I and our customers are using:
![winver-ssso-aad](https://user-images.githubusercontent.com/41962072/43894599-877a4b9e-9bca-11e8-863a-a307ab2fb507.PNG)

This is the error when I attempt to join the machine to an Active Directory whilst the machine is Azure AD joined:
![cannot join to domain and azure ad- domain removed](https://user-images.githubusercontent.com/41962072/43894566-662957e6-9bca-11e8-9c28-bb6a7e22d059.png)

**Comment by joshexltd** [comment] 2018-11-14 13:04
@jmprieur @Nadav-N We have had to change the behaviour of our app so that it prompts for credentials when we encounter the "....cannot contact a domain controller...." exception. Whilst this does provide a workaround which results in successful authentication it is not ideal. Is there anything else I can provide to progress this?

**Comment by henrik-me** [comment] 2019-06-28 22:29
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.

**Closed by henrik-me** 2019-06-28 22:29 UTC
