### ISSUE TITLE
System.TypeInitializationException on xamarin iOS

### ISSUE THREAD

**Issue by arjensteinhauer** [AzureAD/azure-activedirectory-library-for-dotnet#1507] opened 2019-02-22 07:42 UTC
**Which Version of ADAL are you using ?**
ADAL 4.5.1

**Which platform has the issue?**
xamarin iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [X ] Interactive
    * [x] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

**Is this a new or existing app?**
The app is in production, and I have upgraded to a new version of ADAL

**Repro**

```csharp
var authContext = new Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext(authority);
```

**Expected behavior**
An instance of the AuthenticationContext class is created and can be used to authenticate the user.

**Actual behavior**
The Xamarin app is used on three platforms; Android, Windows UWP and iOS.
When upgrading the ADAL library from version 3.19.8 to the latest stable version 4.5.1 the app throws an exception only on the iOS devices when try to login using the ADAL library. The exception occurs when creating a new instance of then Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext class.

The exception thrown:
Message of type System.TypeInitializationException occured: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache' threw an exception.
Attempting to JIT compile method 'Microsoft.Identity.Core.iOSTokenCacheAccessor:GetTeamId ()' while running in aot-only mode. See https://developer.xamarin.com/guides/ios/advanced_topics/limitations/ for more information.
at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.ctor (System.String authority)

**Additional context/ Logs / Screenshots**
If you like I can provide a working visual studio solution with only the login code left (no production code) when needed for further analysis.

**Comment by jmprieur** [comment] 2019-02-22 10:49
@arjensteinhauer : 
- do you have repro steps that we could follow?
- Otherwise, is it an option for you to use MSAL.NET (the next generation of auth libraries) ? 
  - there is a good documentation on platform specifics. For instance see [MSAL.NET - Xamarin iOS Specifics](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/Xamarin-iOS-specifics)
  - there is a sample that you can run as is or adapt: 


   Sample | Platform | Description 
   ------ | -------- | -----------
   [https://github.com/Azure-Samples/active-directory-xamarin-native-v2](https://github.com/azure-samples/active-directory-xamarin-native-v2) | Xamarin iOS, Android, UWP | A simple Xamarin Forms app showcasing how to use MSAL to authenticate MSA and Azure AD via the AAD V2.0 endpoint, and access the Microsoft Graph with the resulting token. ![](https://github.com/Azure-Samples/active-directory-xamarin-native-v2/blob/master/ReadmeFiles/Topology.png)

**Comment by arjensteinhauer** [comment] 2019-02-22 11:27
**MSAL.NET**
Using MSAL.NET is not an option for now. This is planned for future releases of our app, when the AAD v2.0 endpoints for all our customers are up-and-running.

**Repro steps iOS platform**
Our app is running on all platforms (Android, iOS, Windows UWP) for almost a year, using the ADAL library for authentication the user. We have used the provided sample code for the authentication, below then code snippet. This code has been working just fine on all platforms, including iOS.

`var authContext = new AuthenticationContext(authority);`
`UserIdentifier userId = UserIdentifier.AnyUser;`
`var authResult = await authContext.AcquireTokenAsync(resource, clientId, new Uri(returnUri), platformParameters, userId);`

Recently we have upgraded the ADAL NuGet package from version 3.19.8 to version 4.5.1. After this upgrade the app crashes with the mentioned exception when construction AuthenticationContext, only on iOS devices. There has been no code changes in our app, only the NuGet package upgrade. The code runs fine in the iOS simulator but not on a real device.
When I downgrade the ADAL NuGet package back to version 3.19.8, the app just works fine again on the iOS device.

We are using the following app setup:
- Xamarin.Forms (v3.5.0.169047)
- Prism.Ninject.Forms (v6.3.0)
- Microsoft.IdentityModel.Clients.ActiveDirectory (v3.19.8)
- SQLite-net-pcl (v1.5.231)

**Comment by jmprieur** [comment] 2019-02-22 14:11
@bgavrilMS @MarkZuber @henrik-me

**Comment by bgavrilMS** [comment] 2019-02-22 14:49
The exception seems to come from the Xamarin JIT compiler. In ADAL v4 we modified how we store the token cache on iOS and the exception seems to come from that logic

https://github.com:443/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/iOS/iOSTokenCacheAccessor.cs#L88

@arjensteinhauer - how are you packaging your app. Do you have any settings related to AOT compiling?

CC @jennyf19 in case she has seen this before. We may need to reach out to the Xamarin folks for help on this one.

**Comment by arjensteinhauer** [comment] 2019-02-25 08:16
> @arjensteinhauer - how are you packaging your app. Do you have any settings related to AOT compiling?
- Using the standard Azure DevOps build pipeline:
  - specific **iOS Build** settings:
    - Linker Behavior: Don't Link
    - Supported Architectures: ARMv7 + ARMv7s + ARM64

**Comment by jennyf19** [comment] 2019-04-15 22:01
@arjensteinhauer I was unable to repro the issue. I created a new Xamarin iOS app, installed 3.91.8, did acquire token interactive, then updated to 4.5.1, and was able to do a silent call (the cache was used). I cleared the cache, signed-in again successfully, and then updated to 5.0.2-preview and had no issues.

I'll reach out to a contact w/Xamarin iOS, but as of now, am not sure what the issue is.

Have you considered moving to 5.0.2-preview to see if it repros there as well?

**Comment by mandel-macaque** [comment] 2019-04-16 10:10
@bgavrilMS @jennyf19 can you please let me know how I can get the branches that you have used to release v4 and the previous version? I'd like to see the changes that @bgavrilMS mentions regarding the token cache. 

@arjensteinhauer I would appreciate a full stack trace (unless it was added already and I missed it, then a pointer to it would be nice). I full build log, if possible, would be nice too (via a gist for example).

I'll take a look at the information provided and either will provide pointers to the possible fix our we can drag the right person from the mono team to take a look.

**Comment by bgavrilMS** [comment] 2019-04-16 12:46
ADAL repo - dev branch was used to release. All releases have been tagged. 

![image](https://user-images.githubusercontent.com/12273384/56210597-0ccd2f80-604e-11e9-92e9-ee5d96b444fc.png)

**Comment by mandel-macaque** [comment] 2019-04-16 18:26
Hello,

I have taken a closer look, there is no real reason for the method to be using the JIT compiler. Having said that, we have had some issues in the past with the AOT compiler. 

To be clear, I have tested the GetTemId method (only the GetTeamId) with a iOS application with the following:

* [Xamarin.iOS master](https://github.com/xamarin/xamarin-macios/commit/cf8d42e4c0de067664ddc770de24199c884566e8) with an iPhone 8+ on release mode "Don't Link": Test success.
* [Xamarin.iOS mono-2019-02](https://github.com/xamarin/xamarin-macios/commit/9bd927bb7fe3eb1b14721745c500ff8b4aecd109) (branch with the next mono release) with an iPhone 8+ on release mode "Don't Link": Test success.

To look into it further, I would need the full version of the runtime from @arjensteinhauer  

We might be talking about a mono issue that was already fixed or another possible issue. Full build logs will also be nice to see what are the exact parameters passed to the compiler to be able to reproduce it.

Sample app used (not much code, we might need a closer app to the one failing to get more info)

[TestSecRecord.zip](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/files/3086347/TestSecRecord.zip)


PS: Xamarin.Froms and Xamarin.iOS version are not related.

**Comment by bgavrilMS** [comment] 2019-06-11 11:47
This seems to be Xamarin problem that occurs in certain configuration. 

We don't use that static constructor for TokenCache in MSAL (and generally they are not used a lot), so migrating is probably a workaround.

**Comment by jennyf19** [comment] 2019-06-11 17:15
@mandel-macaque Any thoughts on this? Are you aware of any similar issues w/Xamarin iOS? Thanks.

**Closed as completed** 2019-06-27 17:41 UTC
Labels: External, Can't Repro, More info needed, scenario:iOS
