### ISSUE TITLE
Main Project referencing a library that includes ActiveDirectory NuGet requires reference to package also

### ISSUE THREAD

**Issue by jamesmundy** [AzureAD/azure-activedirectory-library-for-dotnet#511] opened 2016-08-03 09:49 UTC
Two of us on StackOverflow have noticed this issue after updating to the latest version of the ActiveDirectory nuget package so I thought I'd notify you here and see if this is indeed an issue: http://stackoverflow.com/questions/37940169/nuget-reference-behaves-in-a-strange-fashion

Basically, I have a asp.net web project which references a library which I use to retrieve tokens securely from Azure KeyVault which requires a reference to this nuget package. All was working fine until I updated the nuget package to the latest version today.

Every time I try to make a request that uses the library I receive the following exception:
`Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
</ExceptionMessage>
<ExceptionType>System.IO.FileNotFoundException</ExceptionType>
<StackTrace>
at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) at System.Reflection.Assembly.Load(AssemblyName assemblyRef) at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.LoadPlatformSpecificAssembly()
</StackTrace>`

If I then include the ActiveDirectory in the top level web project everything works ok. As far as I know you shouldn't have to do this. Downgrading the package to a much older 2.28 (the version I was using before) works just fine.

 It's similar to an issue I have experienced with Xamarin.iOS/Android and the linker which can strip out references.

Any ideas?

**Comment by sjwaight** [comment] 2016-08-16 12:15
Note this behaviour is particularly destructive in Azure Functions... where the code appears to work for a period then starts throwing this error. I downgraded to 3.12.0 and will monitor behaviour.

**Comment by kpanwar** [comment] 2016-08-16 16:47
@sjwaight - Are you saying that this particular issue does not manifest in 3.12, but it does in 3.13?

@jamesmundy - You are comparing ADAL v2 to v3. It is a major release where we make breaking changes. ADAL v3 uses "Portable Library + Platform Specific Library" model to allow for dependency injection at runtime. v3 does not use older profile based nuget packaging (which worked for you).
Platform specific DLLs are included automatically via nuget referencing when your project type is net45/iOS/Android/UWP.

**Comment by sjwaight** [comment] 2016-08-16 21:47
So far since dropping in 3.12.0 I haven't seen this issue.  Note that Azure Functions only supports 'net46' project types so I am wondering if that is causing nuget to not retrieve the right platform-specific components. Having said this I am at a loss as to how 3.13.1 worked for ~ half a day then started throwing this error.

**Comment by kpanwar** [comment] 2016-08-16 22:19
@sjwaight - can you move to 3.13.1 and ensure that you actually are using it? Lets see that if this problem happens again. I find it hard to believe that this exception would happen after half a day.

**Comment by sjwaight** [comment] 2016-08-17 00:03
Can confirm that updating to 3.13.1 immediately throws an exception - 3.12.0 is fine. Azure Functions App environment 0.4 (which only support 'net46' projects). Stack trace is below.

System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin' threw an exception. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: Assembly required for the platform not found. Make sure assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' exists ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.LoadPlatformSpecificAssembly()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.LoadPlatformSpecificAssembly()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.InitializeByAssemblyDynamicLinking()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin.get_Logger()
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority)
   at Submission#0.GraphClient.<SendGraphGetRequest>d__1.MoveNext() in D:\home\site\wwwroot\MyProcessor\run.csx:line 85

**Comment by kpanwar** [comment] 2016-08-17 01:17
@sjwaight - I am not sure how your project is set up, but I tried to repro the same by creating a console app that requires minimum .NET 4.6.1 and was able to use the library with no issues. Also, platform specific components are bundled in a single nuget and are not packaged separately. 
Can you share a repro project?

**Comment by sjwaight** [comment] 2016-08-17 01:50
I have created the simplest demonstration I can here: 

https://github.com/sjwaight/adalazurefunctionsissue

Note we are running against B2C but the error does not seem related to that.

In order to get the demonstration running you will need to deploy the contents of the three files into an Azure Functions App (copy / paste of contents will suffice) and then update the necessary Guids / credentials.

**Comment by sjwaight** [comment] 2016-08-17 02:14
Note that after running an Azure Function for a period with 3.12.0 I have also run into the same issue with 3.12.0 - is there some form of internal buffer that only requires a logging event after a certain period of time?

**Comment by jamesmundy** [comment] 2016-08-17 11:31
@kpanwar sorry I downgraded to v2.x as that was what I was using previously. I didn't have time to roll out other versions to production to test.

**Comment by kpanwar** [comment] 2016-08-18 16:54
@sjwaight - There is no internal log buffer. If the platform DLL was missing the API would fail right when you try to initialize AuthenticationContext. I am not sure how Azure Functions work and how can I debug their procedure to load modules.

**Comment by sjwaight** [comment] 2016-08-18 23:30
Please note I find the resolution of this via "closing" to be unacceptable and simply saying you don't understand Azure Functions doesn't help solve my issue. It makes it hard to push ADAL / AAD / Azure Functions as a viable model for production systems.

**Comment by kpanwar** [comment] 2016-08-18 23:32
I did not mean to close it. I was responding to it via phone.

**Comment by sjwaight** [comment] 2016-08-18 23:59
OK, great! Let me know if there is anything else I can do to help identify root cause. I have a Function that isn't displaying this issue but that is not receiving a large number of calls in a short period - might this be a locking issue of some variety? (I am just throwing out ideas so apologise if they make no sense)

**Comment by kpanwar** [comment] 2016-08-24 03:34
I checked again and I don't see a case where this would manifest in the future after creation of a function. Everytime the function is invoked, you are creating a new instance of the authentication context. see if creating a singleton instance would help. I think it would.

**Comment by ericgrover** [comment] 2016-08-24 12:51
This issue has nothing to do with the way the library is being used.  The package is broken.  I can reproduce this problem easily by just creating a solution with 2 class libraries.  If I add the latest ADAL to one, then reference it in the other lib, when you build, it does not copy over the platform dll into the referencing lib's bin folder.

This is the 2nd case I have seen where key nuget packages are being broken as they begin targeting .net core.  System.Net.Http is also broken.  We are back living in DLL hell with nuget.

**Comment by kpanwar** [comment] 2016-08-24 16:33
@sjwaight's problem is different. it works for him for sometime and then it does not.

@jamesmundy and you have the same problem. The issue can be circumvented by adding ADAL library reference to both the projects. It sucks, but it works.

**Comment by ericgrover** [comment] 2016-08-24 16:37
Adding it to the second library completely defeats my application architecture where I have a separation of concerns.  I don’t want to tightly couple a dependency on ADAL to every assembly that injects the service that uses it.

**Comment by jamesmundy** [comment] 2016-08-25 08:17
Agree with @ericgrover here, we both have the same issue and you shouldn't have to add the NuGet package to both libraries. It does work but it still really needs to be fixed.

**Comment by kpanwar** [comment] 2016-08-25 16:15
This is something that needs to be addressed by nuget folks. As one of you pointed out, it could be due to the changes in the way core clr is handled by nuget.

**Comment by kpanwar** [comment] 2016-09-13 12:46
http://www.codiply.com/blog/dependency-injection-across-multiple-layers-with-ninject/

This shows why you are seeing the problem. Platform DLL is only used via dependency injection and ends up getting stripped by the linker.

**Comment by kpanwar** [comment] 2016-09-28 19:24
@jamesmundy @ericgrover - I am going to close this issue soon as I have already shared why you are seeing a given behavior. Please let me know if you have any other questions.

**Comment by ericgrover** [comment] 2016-09-28 20:09
@kpanwar So I understand that it is a linker issue caused by the use of DI.  The question is, will this get fixed in the nuget package?

**Comment by rahulseth01** [comment] 2016-09-29 15:06
I am facing the same error with "Microsoft.IdentityModel.Clients.ActiveDirectory" version 3.13.x and .Net Framework 4.5.

To repro :- After adding the Nuget and clean the Solution and Debug.
Since left with no option, moved back to Version 2.28.x  :-(

**Comment by kpanwar** [comment] 2016-09-29 15:34
@ericgrover - I am not sure how can this be resolved in nuget package without a dependency resolver.

**Comment by ericgrover** [comment] 2016-09-29 18:25
If you are implying that in order to use this nuget package that it is up to the consumer to architect their app in a certain way (differently than in previous versions of the package), then you need to go back to the drawing board.

**Comment by kpanwar** [comment] 2016-09-29 18:27
@ericgrover - I am not. I am looking for suggestions. Do you have any?

**Comment by ericgrover** [comment] 2016-09-29 18:58
Well, it would seem that the DI scheme that you are using needs to be rethought as it does not meet the requirements of usage.  It might be that there will need to be separate nuget packages per platform.  I know that is not the ideal, but until another way is devised, it may be necessary.

**Comment by kpanwar** [comment] 2016-09-29 19:04
Best way would be to move to netstandard. That will Make things work as you expect. But they don't have unified API surface for UI interact and no support for winforms either. Being between a rock and a hard place, current DI approach seems to be the only viable option.

**Comment by chaneg06** [comment] 2016-12-20 15:41
Was this ever resolved?  I am having the same exact issue.  The Platform dll is not copying and I have to add the package to both of my projects

**Comment by kpanwar** [comment] 2016-12-20 16:19
As discussed, there is no resolution for this currently

**Comment by isabekyan** [comment] 2016-12-26 19:29
There's some temporary workaround:
In a core project where u have dependency on nuget package add some code (method) that explicitly uses a type from `Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll` e.g.:
```C#
        private static void SomeMethodToLinkPlatform()
        {
            var creds = new UserPasswordCredential("testUser", "SomePassword");
        }
```

After that, referencing this project will add ...Platform.dll to resulting build in other projects.

**Comment by aurelienprevotMVP** [comment] 2017-01-15 18:40
Hi guys,
Same problem here, resolved by importing all the DLLs in the folder...

**Comment by spooky** [comment] 2017-01-31 16:29
Same problem.
Are there any plans to fix this?

**Comment by kpanwar** [comment] 2017-01-31 16:39
No plans at the moment.

**Comment by Molibar** [comment] 2017-02-24 13:00
Isn't this a manifestation of the classical low-coupling problem; where dependencies are resolved at run-time, and therefore the Deploy Tools doesn't realise it has to copy certain Assemblies that aren't referenced at Compile Time? I think isabekyan's solution, in one way, shape or form, is the only viable for this problem. I don't think this is a NuGet-package problem.

**Comment by aronbardsley** [comment] 2017-02-28 11:28
So glad i found this thread.

Exactly the same problem as sjwaight. The project worked for a day or so, then just started failing
Downgrading to "Microsoft.IdentityModel.Clients.ActiveDirectory": "3.12.0" is working for now.

**Comment by jmprieur** [comment] 2017-03-15 14:39
@duncanpMS I believe this is similar to a problem you have encountered. Do you have an opinion on how to fix this?

**Comment by MurrayFoxcroft** [comment] 2017-04-04 14:38
This is one of the most horrible "bugs" I have come across. Any chance of sacrificing the dependency injection in the code (!shock!) for usability.

**Comment by kpanwar** [comment] 2017-04-04 14:47
This is how linker works. This is not a "bug". The design in place has been what was recommended to the humanity for building cross platform apps using PCL. There are ways with modern toolings of VS2017 to fix this but there is no immediate plan to address this.

**Comment by kspearrin** [comment] 2017-05-15 14:42
Fixed with @isabekyan's workaround above.

**Comment by jmprieur** [comment] 2017-06-06 14:20
We don't have plans to fix this. Closing as "By design"

**Comment by Maggern3** [comment] 2017-06-28 18:29
Hi, I know I'm late to the party and it's marked as by design but I get this error with **linking set to Don't Link.** 
The iOS project does reference the platform assembly.
I've tried everything;
Referencing ios' platform assembly in my PCL.
Referencing net45 platform assembly in my PCL and having `var creds = new UserPasswordCredential("testUser", "SomePassword");` in my PCL.
Adding platform specific code to my AppDelegate; `new PlatformParameters(Window.RootViewController);`
Adding platform specific code to my PCL; `var x = typeof(Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters);`

Downgrading to 3.12.0.

The only way I get your library to work, is if I build debug builds.

The exception is similar to the exception below just with using the latest version(3.14).
System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformPlugin' threw an exception. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: Assembly required for the platform not found. Make sure assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' exists ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform, Version=3.13.1.846, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by mjcheetham** [comment] 2017-06-30 12:11
Hi @Maggern3,

I have been unable to reproduce the error you are facing on versions above 3.12.
See an example solution [here](https://github.com/mjcheetham/ADALXamariniOSSample) which has an iOS app and a PCL which uses ADAL.NET 3.14.1.

Please could you share a solution/projects which exhibits the issue you are facing so we might investigate further?

Can you also confirm whether or not the _Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll_ file exists in your built _.app_ package?

Thanks

**Comment by peteski22** [comment] 2017-08-18 10:28
What is going on with this, given that it's been more than a year and people are still seeing this issue in the latest (at the time of writing `3.16.0` - released August 5th 2017) version **still** has this problem?

As people have sensibly suggested earlier in the thread having a project which abstracts away the dependencies on MS libs **shouldn't** then have to reference them or be tied to them, I'm pretty shocked MS would be recommending to developers to do this. 

This can't be a case, of "by design" or "won't fix", come on guys.. get this sorted out!

**Comment by jmprieur** [comment] 2017-08-18 11:21
@peteski22, thanks for the feedback, and sorry if we did not change the label on this issue

the next release of ADAL.Net (3.17) will only provide a NuGet package with only one assembly per platform (named 'Microsoft.IdentityModel.Clients.ActiveDirectory.dll). the 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll won't exist any longer (the platform specific code is in the assembly for each platform now). This should solve the problem you have.
The code is already committed in the dev branch

**Comment by peteski22** [comment] 2017-08-18 12:24
@jmprieur thanks for getting back to me quickly! Any idea on a estimated release date for the updated nuget package?

**Comment by Cryan24** [comment] 2017-08-22 08:40
re: The above comments about downgrading to fix, this worked, but I had to downgrade to version 2.28.4 instead of  3.12.0 to get going again. My Target .Net framework is 4.5.2. I hope this helps someone else :)

**Comment by abergs** [comment] 2017-08-23 17:35
I just ran into this with my WebApi framework (and my classlib) running .net fw 4.6.1.

**Comment by nh2d** [comment] 2017-08-24 08:48
We ran into an issue here where the DLL works on local runs, but when deployed to azure api service it fails. This caused a production failure for us (for a luckily non-critical job). Also using .net 4.6 and during an upgrade of nuget.

**Comment by peteski22** [comment] 2017-09-18 12:44
@jmprieur any idea on the release date for 3.17?

**Comment by pauldalyii** [comment] 2017-10-03 16:03
@jmprieur & @kpanwar, I'm seeing a very similar, but different issue in an Azure Function targeting net47 that references a .NET Standard 2.0 library that references `Microsoft.IdentityModel.Clients.ActiveDirectory`, v3.16.1:

`Exception while executing function: Applications_Get. Security: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.16.1.24801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621). System.Private.CoreLib: Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.16.1.24801, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.`

I do not get the error message from the OP regarding 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platforms.dll'

I've tried referencing Microsoft.IdentityModel.Clients.ActiveDirectory directly in the function project as well as in the library.  I have also tried adding binding redirects as described in dotnet/standard#481

Do you think that 3.17 will also resolve this, or should I open a separate issue?

Also, as @peteski22 asked, do you have a rough time frame for 3.17?

**Comment by pauldalyii** [comment] 2017-10-03 23:49
3.17 was released today.  It appears not to have solved the issue I described above.  I'll open a new issue.

**Comment by kloopdogg** [comment] 2017-10-06 13:52
I was experiencing this issue, and upgrading to 3.17 fixed it for me.

**Comment by tomgruszowski** [comment] 2017-11-05 23:03
This is still broken in 3.17.1 Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform

**Comment by geekcubed** [comment] 2017-12-14 08:21
Just ran into this issue myself.  Multi-project solution (targeting .net Full 4.6.2) - middleware includes the Microsoft.IdentityModel.Clients.ActiveDirectory package (v3.17.2) which compiles fine and spits out both dll's when it builds.

Web tier then consumes middleware project, but only the core `Microsoft.IdentityModel.Clients.ActiveDirectory.dll` is copied over when building - the `.platform` dll is missing.

Workaround is to install the package into all my front-end tiers which consume the middleware, which is definitely a smell: short answer is that this package is currently broken.

**Comment by CarlosOnline** [comment] 2018-04-05 13:33
Ran into this issue with .net core 2.0.

Can this be fixed?
Where can I get the .platform dll?

Could not load type '**Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters**' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory.Platform

**Comment by CarlosOnline** [comment] 2018-04-05 15:16
Yes, but didn't help - still fails.

```
<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.19.2" />

    <Reference Include="Microsoft.IdentityModel.Clients.ActiveDirectory.Platform">
      <HintPath>..\packages\Microsoft.IdentityModel.Clients.ActiveDirectory.3.19.2\lib\net45\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll</HintPath>
    </Reference>
```

**Comment by shawnjones253** [comment] 2018-04-07 06:29
I'm also running into this problem with 3.17.2

**Comment by jmprieur** [comment] 2018-04-08 01:09
what is the target platform of your library?
did you try 3.19.2?

**Comment by shawnjones253** [comment] 2018-04-11 23:50
Targeting .NET 4.7 (Any CPU)
I just tried both 3.19.2 and 3.19.3. In both cases, the project that directly references ADAL gets both .dll files in its output, while the upstream project referencing the first project ends up missing the platform dll.

**Comment by jmprieur** [comment] 2018-06-12 06:16
@shawnjones253 @CarlosOnline 
Indeed, my impression is that you'd want your project referencing directly ADAL.NET to be a multi-targeting project (like ADAL.NET)

cc: @henrik-me for confirming.

**Comment by henrik-me** [comment] 2018-06-12 16:45
I would try evaluate if the references are actually setup in both projects. It's possible that nuget restore failed.

**Comment by tmandekic** [comment] 2018-06-22 16:19
Not sure if this is the same issue: 

-  when i use Microsoft.IdentityModel.Clients.ActiveDirectory in Service Fabric Stateless Service (Asp.Net Core 2), PlatformParameters is parameter-less (that's what led me to this thread). 

- when  I implement the same code and ADAL package with Service Fabric Stateless Service (.net 4.6), all is well (PlatformParameters expects correct parameters). 
Thank you for opening this issue.  

Edit:  

- In Visual Studio 2017 (Community, V 15.5.7) create Service Fabric Stateless Service project, with Asp.Net Core 2 template. Add reference to Nuget package Microsoft.IdentityModel.Clients.ActiveDirectory v 3.19.8 (actually any version exhibits the same behavior).
 In the stateless service create new method and add code:  
```
var p = new PlatformParameters(PromptBehavior.Auto); 
  
AuthenticationContext authContext = new AuthenticationContext(authority); 

AuthenticationResult authResult = await authContext.AcquireTokenAsync(resource, clientId, new Uri(redirectUri),parameters);  
```

compile error on first line (`var p = new PlatformParameters(PromptBehavior.Auto);`):  
'PlatformParameters' does not contain a constructor that takes 1 arguments.

If I try to force it with:
          ` ((Microsoft.IdentityModel.Clients.ActiveDirectory.PlatformParameters)parameters).PromptBehavior = PromptBehavior.Always;
`  
compile error is: 'PlatformParameters' does not contain a definition for 'PromptBehavior' and no extension method 'PromptBehavior' accepting a first argument of type 'PlatformParameters' could be found'  
 

- If I follow the same steps and code in Visual Studio 2017, with Service Fabric Stateless Service  .Net 4.6 framework template, the code works as expected.   

Edit 2: 
Same issue in Visual Studio Community 2017 v15.7.4

**Comment by henrik-me** [comment] 2018-06-22 17:18
@tmandekic : can you pls. describe a bit more which issues you are seeing and how to reproduce them? @bgavrilMS for awareness on a potential packaging issue, however the later comment here seems though to point out the differences in platform parameters based on platform. There are some intentional differences but it's currently unclear to me in this story whether this is what is being asked for here. @tmandekic pls. help adding all the information you can on the issue you are seeing. Not sure those are the same as the original issues mentioned in this thread.

**Comment by bgavrilMS** [comment] 2018-06-22 19:08
@tmandekic - regarding PlatformParameters, this class is implemented differently on target framework - it is pretty much empty for dotnet core (since dotnet core does not have UI), and has a lot of options on net45 (e.g. https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/dev/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/netstandard1.1/PlatformParameters.cs)

My feeling is that you are taking a dependency on the net45 assembly instead of the netstandard1.3 one . Are you running the latest version of VS (currently 15.7.4)

**Comment by tmandekic** [comment] 2018-06-22 19:29
While my VS is updating, if I may ask another question: for communication from ServiceFabric StatelessService to WebAPI, where WebAPI is using B2C auth, which auth flow should I follow? (there is no browser or specific user involved). 
I am considering [device profile](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Device-profile-for-devices-without-web-browsers). Is that correct, or should I look into something else?

**Comment by jmprieur** [comment] 2018-06-22 20:04
@tmandekic 
I'd say that the [client credentials](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows) flows (with application password or with certificate) would be the most adapted if you don't want to call the Web API in the name of a user:

**Comment by TahaAhmad** [comment] 2018-07-27 12:23
Please note the StackOverflow post linked in the original post at the top was created by me and I am frustrated as to why this issue is still not resolved.

It's been almost 2 years and this problem is still happening with Microsoft.IdentityModel.Clients.ActiveDirectory version 3.17.3

In my solution I have a Service Fabric actor targeting .NET Core 2.0 and another authentication Project which is targeting .Net Framework 4.6.2. The authentication project has a reference to the ActiveDirectory library (version 3.17.3) and uses the ADAL library to generate tokens.

My Actor project does not have a reference to the ADAL library and calls the authentication project to get tokens as string. But doing so throws an error saying that the ADAL library could not be loaded:

Could not load file or assembly Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.17....' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 

Help would be appreciated!

**Comment by RogerDavidClarke** [comment] 2018-09-13 16:40
I'm using a standard Xamarin forms project with Android and I'm getting exactly the same issue with both the platform dll not being present in the Bin folder. The Platform dll is not copying and I have to add the package to both of my projects. All of these Xamarin forms projects have the mainpage code sitting in a class library. The recurring common issue is PlatformParameters not accepting any parameters due to being pull from the .NET Standard 2.0 framework. I've spend days investigating this and its really frustrating to see that MS has not fixed in 2 years. Really 2 years!

Is there a published workaround or even better, a fix, that can be applied to a Xamarin forms project? My project is now in delay  mode because of these issues.

**Comment by jmprieur** [comment] 2018-09-14 05:16
@bgavrilMS FYI.

**Comment by bgavrilMS** [comment] 2018-09-14 05:58
@RogerDavidClarke - you don't need the platform dll unless you are upgrading from an older version of ADAL and don't want to rebuild your code as a few types have moved namespace. The paltform dll only contains type forwarding.

As for PlatformParameters - they are platform specific as the name suggest, so you cannot construct them in your netstandard library. What you can do however is to construct PlatformParameters on each of your entry point projects (e.g. Android, iOS, UWP) and inject them back to the netstandard library. In fact, Xamarin provide their own simple DI - https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/dependency-service/introduction

Let me know if you need a sample on how to achieve this.

**Comment by bgavrilMS** [comment] 2018-10-02 15:46
@jmprieur - proposing to close this, I don't see what can be done here.

**Comment by jmprieur** [comment] 2018-10-02 15:50
@bgavrilMS Agreed. changed the labels, and closed

**Closed by jmprieur** 2018-10-02 15:50 UTC
Labels: By Design

**Comment by JohnGalt1717** [comment] 2018-10-31 18:23
4.3.0 still does this and a rebuild doesn't fix it.

Specifically when working with the Azure Media Services latest api it will throw when doing a query against assets.

**Comment by bgavrilMS** [comment] 2018-10-31 20:02
@JohnGalt1717 - please open a new bug and provide a repro. This issue is very old and convoluted, there are multiple issues reported on this thread etc.

**Comment by acg9** [comment] 2019-04-18 22:03
Faced this today with .Net Core 2.2 using the Microsoft.Extensions.Configuration.AzureKeyVault 2.2.0 package.

Solved it by disabling warning-as-error NU1605 and by manually adding the following to my csproj.

```xml
<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.14.2" />
```
