### ISSUE TITLE
multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more arguments (e.g. UserId)

### ISSUE THREAD

**Issue by XuYanXya** [AzureAD/azure-activedirectory-library-for-dotnet#1609] opened 2019-06-05 18:15 UTC
**Which Version of ADAL are you using ?**
We're using Microsoft.IdentityModel.Clients.ActiveDirectory.3.17.2

**Which platform has the issue?**
We're using .net platform

**What authentication flow has the issue?**
Web App - Authorization code - Access token retrieval

Other? - please describe;

**Is this a new or existing app?**
The app is in production, uses the same version of ADAL, but started seeing this issue

**Expected behavior**
I expect the access token to be retrieved to initialize AAD protected resource as normal.

**Actual behavior**
ADAL exception (multiple_matching_tokens_detected) is thrown and web app freezes because of unable to retrieve access token.

**Additional context/ Logs / Screenshots**
A description about how we use it:
When user signs in, gets authenticated and redirected back to our app, we populate our token cache by exchanging the authentication token for access token and put the access token to redis cache.
![image](https://user-images.githubusercontent.com/51417643/58978998-ebe9a680-8781-11e9-9a04-3743ddb45eea.png)
Later we'll retrieve the access token from cache to create client to communicate with AAD protected resources, such as graph client, etc. by using the code sample below:
![image](https://user-images.githubusercontent.com/51417643/58979126-2d7a5180-8782-11e9-9218-dbc17ea7d88f.png)

This is the stack trace. Could you shed some light on what could go wrong?
Thanks!
![image](https://user-images.githubusercontent.com/51417643/58979585-3586c100-8783-11e9-95ce-fa07008ed055.png)

**Comment by mathyscott** [comment] 2019-06-05 19:07
Same thing has been happening for us on 3.19.8 for about a month now.

**Comment by jmprieur** [comment] 2019-06-05 19:17
@XuYanXya @mathyscott : are there users present in several clouds?

**Comment by XuYanXya** [comment] 2019-06-05 19:22
@jmprieur Could you clarify what do you mean by several clouds?

**Comment by jmprieur** [comment] 2019-06-05 19:27
sorry, I was not clear, @XuYanXya. I meant [National clouds](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-national-cloud)

**Comment by XuYanXya** [comment] 2019-06-05 20:01
@jmprieur Thanks for providing the doc. So far, we're only using Azure AD (global service). So there is no users present in multiple clouds.

**Comment by jmprieur** [comment] 2019-06-06 18:27
Another question for you @XuYanXya : would you have a user who would have kept the same account, but changed the email address associated with the account?

**Comment by XuYanXya** [comment] 2019-06-06 18:57
@jmprieur I can give more info:
The customer has 2 emails: A@outlook.com and B@company. B@company is made an alias of A@outlook.com.
When he tries to sign in with B@company, he was prompted that his email is used with more than one accounts from Microsoft (both work account and personal account).

I'm not sure if the customer ever changed his email address associated with one account. Why does this matter?

We found the multiple_token exception is thrown because this method in the library returns more than one values:
![image](https://user-images.githubusercontent.com/51417643/59058596-d8a60c00-8851-11e9-93e6-acfbbc2afb31.png)
For our case, the uniqueId is user's object id. So it should be unique enough to find at most one values, right?
Also I checked our redis cache, querying with the user's object id doesn't really show any cached token, so it's a cache miss. I'm really confused why this is happening.

**Comment by XuYanXya** [comment] 2019-06-06 19:00
@jmprieur Also do you have a recommended version to upgrade to without breaking changes?

**Comment by MarkZuber** [comment] 2019-06-06 20:31
@XuYanXya Based on your comment that B@company is an alias for A@outlook.com, these will be the same account with the same object id.  this is very likely what the problem is and is equivalent to having the user change their email address on their @outlook.com account (the account itself and it's objectid stays the same).  Are you doing your lookup based on UPN/DisplayableId or based on objectid?

**Comment by MarkZuber** [comment] 2019-06-06 20:42
I'm also confused about your statement that your redis cache doesn't have anything for the user.  Your redis cache is (presumably) what you're using to populate the ADAL tokencache, so it sounds like it's populated with something since you're seeing more than one response from AcquireTokenSilent.  Can you please clarify some of your scenario?

**Comment by henrik-me** [comment] 2019-06-28 22:51
Closing as there haven't been any response for 22 days.

///

Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.

**Closed as completed by henrik-me** 2019-06-28 22:51 UTC

**Comment by banoslo** [comment] 2022-01-06 10:28
The problem was solved for me after I had deleted the local storage and all cookies in my development browser.
