### ISSUE TITLE
Adal 4.4 can't acquire token using Integrated authentication on Windows

### ISSUE THREAD

**Issue by myurashchyk** [AzureAD/azure-activedirectory-library-for-dotnet#1478] opened 2019-01-10 08:50 UTC
**Which Version of ADAL are you using ?**
ADAL 3.19.8, ADAL 4.4.2

**Which platform has the issue?**
net45

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ ] Interactive
    * [x] Integrated Windows Auth
    * [ ] Username Password
    * [ ] Device code flow (browserless)
* Web App
    * [ ] Authorization code
    * [ ] OBO
* Web API
    * [ ] OBO

Other? - please describe;

**Repro**
We have password hash synchronization with Azure AD configured and want acquire token for current user silently. With ADAL 3.19.8 we are getting token as expected, but ADAL 4.4.2 throws exception on the same code.
```csharp
            try
            {
                var context = new AuthenticationContext("https://login.microsoftonline.com/{aad}");
                var result = context.AcquireTokenAsync(resource, client, new UserCredential()).Result;
                Console.WriteLine(result.AccessToken);
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            Console.ReadKey();
```

**Expected behavior**
Token should be acquired without error.

**Actual behavior**
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: Integrated Windows Auth is not supported for managed users. See https://aka.ms/adal-iwa for details.

**Possible Solution**

**Additional context/ Logs / Screenshots**
[Information][False]: 2019-01-10T08:43:40.7200168Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: ADAL PCL.Desktop with assembly version '4.4.2.0',
file version '4.4.2.0' and informational version '4.4.2' is running...
[Information][True]: 2019-01-10T08:43:40.7200168Z: af17f266-f509-4360-8395-8a38b
0a044a1 - AdalLoggerBase.cs: === Token Acquisition started:
        Authority: *
        Resource: *
        ClientId: *
        CacheType: null
        Authentication Target: User

[Information][True]: 2019-01-10T08:43:41.0012785Z: af17f266-f509-4360-8395-8a38b
0a044a1 - AdalLoggerBase.cs: Logged in user detected with user name 'User*@domain.com'
[Verbose][False]: 2019-01-10T08:43:41.0012785Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Loading from cache.
[Verbose][False]: 2019-01-10T08:43:41.0012785Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Verbose][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Verbose][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Verbose][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Verbose][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Verbose][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38b0a0
44a1 - AdalLoggerBase.cs: Looking up cache for a token...
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: No matching token was found in the cache
[Information][False]: 2019-01-10T08:43:41.0168900Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Checking MSAL cache for user token cache
[Information][False]: 2019-01-10T08:43:41.0325473Z: af17f266-f509-4360-8395-8a38
b0a044a1 - AdalLoggerBase.cs: Sending request to userrealm endpoint.
[Information][True]: 2019-01-10T08:43:41.2200533Z: af17f266-f509-4360-8395-8a38b
0a044a1 - AdalLoggerBase.cs: User with user name 'User*@domain.com' detected as 'Managed'
[Error][True]: 2019-01-10T08:43:41.2200533Z: af17f266-f509-4360-8395-8a38b0a044a
1 - AdalLoggerBase.cs: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalExcep
tion: Integrated Windows Auth is not supported for managed users. See https://ak
a.ms/adal-iwa for details.

**Comment by WolfgangGogg** [comment] 2019-02-01 15:41
Having the same issue - any updates? In documentation at https://aka.ms/adal-iwa is stated that all users synced from AD should be reported as "federated". My test user is synced but is still reported as "managed". SSO using a Web Browser based flows works like a charm. So i need to fully rebuild the Web Browser flow to get this working? Did anyone solve this or has a working solution?
Thanks!

**Comment by ermescs** [comment] 2019-02-21 17:06
I also have the same issue, in the following scenario:
- Azure AD Connect with Pass-through Authentication
- Seamless SSO configured and enabled

If i try to obtain a token silently using IWA i receive the following error:
```
password_required_for_managed_user: Password is required for managed user
```

The same issue is referenced in Azure-Samples/active-directory-dotnet-native-headless#30
The solution proposed there works, but doesn't provide a completely silent token retrieval experience.
Actually, an Azure login popup window appears but, since Seamless SSO is properly configured, the user is automatically logged in and no interaction is required. Still, there is a window popup, so this is not a completely silent experience.

Based on https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/adal-and-seamless-sso Seamless SSO in Adal .NET should be achieved by using IWA.

Is this a bug or did the specification change?

Please note that the same happens using MSAL:

- IWA fails with 'managed user' error
- Almost silent token retrieval via non-interactive popup window works

**Comment by jmprieur** [comment] 2019-02-22 14:11
@bgavrilMS FYI

**Comment by henrik-me** [comment] 2019-07-01 16:09
We will be investigating this. We are currently busy on delivering updates for MSAL where we have a similar issue open (See reference)

**Comment by bgavrilMS** [comment] 2019-08-01 17:41
@trwalke - this is the root cause of the issue. Users report that this scenario used to work for managed users.

**Closed as completed** 2019-09-11 20:47 UTC
Labels: Fixed, Investigate, regression?
