### ISSUE TITLE
ADAL 3.x will not install in a UWP project

### ISSUE THREAD

**Issue by jamescro** [AzureAD/azure-activedirectory-library-for-dotnet#547] opened 2016-10-06 21:51 UTC
NuGet installation of ADAL 3.x in a UWP project fails because of conflicting downstream dependencies. ADAL v2.28.x is therefore the latest supported version of ADAL that can work in a UWP app.

Errors in output:

Detected package downgrade: System.Text.RegularExpressions from 4.1.0 to 4.0.12 App1.UWP (>= 1.0.0) -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.13.5) -> System.Xml.ReaderWriter (>= 4.0.11) -> System.Text.RegularExpressions (>= 4.1.0) App1.UWP (>= 1.0.0) -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.13.5) -> System.Text.RegularExpressions (>= 4.0.12) Detected package downgrade: System.Text.RegularExpressions from 4.1.0 to 4.0.12 App1.UWP (>= 1.0.0) -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.13.5) -> System.Runtime.Serialization.Json (>= 4.0.2) -> System.Private.DataContractSerialization (>= 4.1.1) -> System.Text.RegularExpressions (>= 4.1.0) App1.UWP (>= 1.0.0) -> Microsoft.IdentityModel.Clients.ActiveDirectory (>= 3.13.5) -> System.Text.RegularExpressions (>= 4.0.12) Version conflict detected for System.Collections. App1.UWP (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> System.Net.Sockets (>= 4.0.0) -> runtime.win.System.Net.Sockets (>= 4.1.0) -> System.Collections (>= 4.0.11) App1.UWP (>= 1.0.0) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-arm (>= 1.0.0) -> System.Collections (= 4.0.10). Package restore failed for 'App1.UWP'. Package restore failed. Rolling back package changes for 'App1.UWP'.

**Comment by aline-almeida** [comment] 2016-10-21 10:33
Same thing here!

**Comment by kpanwar** [comment] 2016-10-24 19:42
duplicate of #542

**Closed by kpanwar** 2016-10-24 19:42 UTC
Labels: Duplicate
