### ISSUE TITLE
Add support for capital bundle ID's

### ISSUE THREAD

**Issue by EldinHb** [AzureAD/azure-activedirectory-library-for-dotnet#1345] opened 2018-10-23 09:45 UTC
**Is your feature request related to a problem? Please describe.**
We have an existing app to which we wanted to add support to use the MS Authenticator broker to login for accounts protected by MDM. 

The existing application has a capital letter in the bundle ID. The broker fails the check to see if the URL domain and bundle ID are the same because it expects a lowercase bundle ID.

**Describe the solution you'd like**
ADAL can check for capital bundle ID's

**Describe alternatives you've considered**
The only alternative is to remove the application from the App and Play store and submit a new one. Which is very bad for the customers.

**Comment by jmprieur** [comment] 2018-10-23 11:41
@Eldin66 : I'm confused about what you suggest? would you suggest that ADAL.NET lower cases the app name in the bundle ID?

**Comment by EldinHb** [comment] 2018-10-23 12:09
@jmprieur 

Sorry, I'll try to clarify. 

At the moment we use ADAL to authenticate users in our Xamarin.Forms application. We wanted to update the app to use the broker to authenticate users because of the benefits. However, this seems impossible because our bundle ID(iOS) and package name(Android) have an upper case letter and ADAL expects a bundle ID and package name with all lowercase letters

EX: com.testapp.Awesomapp
Adal expects: com.testapp.awesomeapp

Because our application has been published we cannot change the bundle ID and package name for the application. Making a new bundle ID and package name would mean that we are uploading a new application to the stores. 

What we would like is for ADAL to accept upper case bundle ID's and package names when using the MS authenticator broker for authentication. 

This exception occurs because of the upper and lower case difference: 
```
Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: source application bundle identifier should be same as the redirect URI domain
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.OAuth2.TokenResponse.GetResult (System.DateTimeOffset expiresOn, System.DateTimeOffset extendedExpiresOn) [0x001ab] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper.ResultFromBrokerResponse (System.Collections.Generic.IDictionary`2[TKey,TValue] responseDictionary) [0x000cd] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper.ProcessBrokerResponse () [0x0008a] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.BrokerHelper+<AcquireTokenUsingBrokerAsync>d__12.MoveNext () [0x001f5] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <7d5a05cfcb09432d8cc656b9d781e54b>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase+<RunAsync>d__53.MoveNext () [0x0069c] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <7d5a05cfcb09432d8cc656b9d781e54b>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenCommonAsync>d__47.MoveNext () [0x000e8] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <7d5a05cfcb09432d8cc656b9d781e54b>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext+<AcquireTokenAsync>d__35.MoveNext () [0x0008b] in <fa9f5e18d8ee44418ec4ecb4855e4e9e>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x00037] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:187 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:156 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in /Library/Frameworks/Xamarin.iOS.framework/Versions/12.0.0.15/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/TaskAwaiter.cs:128 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <7d5a05cfcb09432d8cc656b9d781e54b>:0 
  ```

**Comment by EldinHb** [comment] 2018-10-24 15:04
Any update on this? 

Is there a reason why ADAL + broker only accept lowercase bundle ID's and package names? Right now, existing applications are out of luck if they use upper case letters in their ID's or package names. So I'm guessing that you guys had a valid reason for that implementation. 

I want to add that we are willing to assist with testing.

**Comment by jmprieur** [comment] 2018-10-24 15:25
@jennyf19 FYI
cc: @henrik-me

**Comment by henrik-me** [comment] 2018-10-24 15:52
@Eldin66 : We will likely need to discuss this with the teams building the brokers. Are you seeing the same behavior across iOS and Android. We can make the changes in the client libraries and have you validate however there is likely a change required on the broker side as well.

CC: @jennyf19

**Comment by jennyf19** [comment] 2018-10-24 21:17
@Eldin66 What redirectUri's are you using for [Android](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS#register-a-redirect-uri-for-your-application) and [iOS](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/leveraging-brokers-on-Android-and-iOS#register-your-redirect-uri-in-the-application-portal)?

**Comment by EldinHb** [comment] 2018-10-25 10:59
@henrik-me 
According to the documentation the same behavior should happen on Android as well. But, I just checked it on Android to be sure and it appears to work on Android even though the package name is the same as the bundle ID. I do experience other problems with the Android version, the token does not get cached so the user has to relog after the application closes, but I'll create a new issue for this if necessary (haven't tried to debug that yet). 

EDIT: This happens on a physical device.

@jennyf19 
iOS bundle ID: com.companyname.Appname
iOS redirect URI: companyname-broker-auth://com.companyname.Appname
Exception occurs as described above.

tried it with (encoded): msauth://code/companyname-broker-auth://com.companyname.Appname 
This way the broker does not return or give an error. It simply stays on the broker with no error message as expected.

Android package name: com.companyname.Appname
Android redirect URI: msauth://com.companyname.Appname/signatureid

The Android version seems to redirect correctly.

**Comment by IlyaSemenchenko** [comment] 2019-03-14 09:42
It seems like more than 4 months passed after last action here. We have the same issue and it is a critical blocker for us right now.
Could I get a status about the issue? I can provide all needed information, if needed.

**Comment by jennyf19** [comment] 2019-03-14 15:50
@IlyaSemenchenko We've been prioritizing work on MSAL. Will take a look and get back to you.

**Comment by jennyf19** [comment] 2019-03-15 19:53
@IlyaSemenchenko @Eldin66 Sorry for the delay on this. Have opened an issue in ADAL and MSAL to address the issue.
new Uri() lowercases the redirectUri, which ADAL is sending to broker. Broker is expecting to match the BundleId and RedirectUri, which is case sensitive because BundleId is case sensitive from Apple's perspective. 

Once we have decided on a fix, I'll update the thread here. Thanks for your patience. 
cc: @jmprieur

**Comment by IlyaSemenchenko** [comment] 2019-03-20 12:05
Hi @jennyf19 , thanks for the reply, I already fixed the issue in local repository and could make a Pull Request with the fix.
Please assign the issue to me and I will try to make PR in few day

**Comment by jmprieur** [comment] 2019-06-06 17:48
Duplicate of #1538 
cc: @jmprieur

**Closed as completed by jmprieur** 2019-06-06 17:48 UTC
Labels: bug, scenario:iOS, scenario:Android, broker
