### ISSUE TITLE
DocBug :Adaltrace is not applicable to 3.0+ release?

### ISSUE THREAD

**Issue by amritanshujohri** [AzureAD/azure-activedirectory-library-for-dotnet#782] opened 2017-09-05 07:16 UTC
In readme.md, Under the desktop application. I do see AdalTrace being mentioned and how to use it to log/debug the details this class doesn't exist post 3.0?

**Comment by kpanwar** [comment] 2017-09-05 19:33
duplicate of https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/527

**Closed by kpanwar** 2017-09-05 19:33 UTC
