### ISSUE TITLE
Can't connect to the service in UWP app

### ISSUE THREAD

**Issue by hecongy** [AzureAD/azure-activedirectory-library-for-dotnet#933] opened 2018-01-03 07:20 UTC
Same issue as **afourney** mentioned in [AcquireTokenAsync fails in a UWP app](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/222).

When users (under @microsoft.com) attempt to login from a laptop connected to the corporate network, they receive the error:

"**We can't connect to service right now. Check your internet connection or try this again later**"

But it works fine with users not under @microsoft.com, such as @outlook.com.

What's more, it also works fine with users under @microsoft.com from a laptop connected to other networks rather than the corporate network.

I just recapitulate this issue to see if any solution exists, thanks a lot.

**Comment by kpanwar** [comment] 2018-01-03 21:53
This issue is not because of the library, so it does not warrant to be re-opened. @CharlesHe21 - you also need to enable sharedUserCertificates capability to make it work for microsoft accounts.

**Comment by ghost** [comment] 2018-07-25 12:25
Our app had a similar issue for a long time before we added the sharedUserCertificates and privateNetworkClientServer capabilities, AND upgrading to 3.19.6. However, this seems to have been broken with 3.19.7 (and 3.19.8). The app no longer authenticates our internal users when connected to our VPN/corp network, and they are receiving the following error again:
"We can't connect to service right now. Check your internet connection or try this again later"

Reverting back to 3.19.6 corrects the issue.

**Comment by ghost** [comment] 2018-08-01 12:39
I see this was labeled a bug but the issue is still closed.  Can the issue be re-opened?

**Comment by jmprieur** [comment] 2018-08-01 13:38
Could you please provide repro steps? for instance can you repro this with this sample? https://github.com/azure-samples/active-directory-dotnet-native-multitarget

**Comment by ghost** [comment] 2018-08-03 12:37
I tried the sample and didn't have the issue.  I re-installed the 3.19.8 package in my app and it's working again.  Sorry to trouble you, please re-close the issue.

**Closed** 2018-08-03 13:37 UTC
