### ISSUE TITLE
Token caching fails silently for the act-on-behalf-of scenario when UserAssertion is created with only assertion value

### ISSUE THREAD

**Issue by Hihaj** [AzureAD/azure-activedirectory-library-for-dotnet#249] opened 2015-09-28 21:48 UTC
Background
---
I'm building a web app that uses ADAL to aquire an access token for Dynamics CRM on behalf of the currently logged in (Azure AD) user. The app creates a `UserAssertion` from the logged in user's bootstrap token, like this:

```
var boostrapContext = (BootstrapContext)claimsPrincipal.Identities.First().BootstrapContext;
var userAssertion = new UserAssertion(bootstrapContext.Token);
```

(This pattern was taken from the "official" act-on-behalf-of sample, but was based on an old version, [here](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/ac6926d17827b0fe6853332b53a015728d97b350/TodoListService/Controllers/TodoListController.cs#L132).)

It then aquires an access token using `AuthorizationContext.AquireToken`, passing in the resource ID for Dynamics CRM, app credentials (client id and key) and the above user assertion.

The problem
---
Everything seemed to work as intended until we let the users in for testing. Pretty often, they would report seeing another user's information when the app displayed the current Dynamics CRM user. Eeek!

Investigation
---
After investigating this tonight, the explanation that I've come up with is this:
- Creating a `UserAssertion` instance with only a bootstrap token for act-on-behalf-of results in the `UserName` property being `null` (see [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.Common/UserAssertion.cs#L33)).
- `AquireTokenOnBehalfOfHandler` sets `DisplayableId` to `UserAssertion.UserName`, in this case `null` (see [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.NET/AcquireTokenOnBehalfHandler.cs#L37)).
- Also, `AquireTokenOnBehalfOfHandler` never sets `UniqueId`, which leaves it as `null`.
- When the (default) TokenCache queries for tokens, both `uniqueId` and `displayableId` are null, which means that any token returned will only be matched on authority, client id and subject type - nothing user-specific (see [here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/master/src/ADAL.Common/TokenCache.cs#L445)).

I've created a debug endpoint in the app that displays information about the current claims principal, the bootstrap token, the access token returned from `AuthorizationContext.AquireToken` and all tokens stored in the TokenCache. My findings:

- The claims identity contains the expected, logged on user identity.
- The bootstrap token contains the corresponding user information from Azure AD.
- The aquired token is correct _only for the first person logging in after an app restart_ - other users see the first person's token.
- The token cache only ever contains a single token - the first user's. Presumably, this could get swapped out for another user's token if it would expire and another user happens to log in after that point.

Solution
---
If I instead create the `UserAssertion` using the constructor overload that takes an assertion type and username in addition to the assertion value, everything works as expected. This is indeed how the act-on-behalf-of sample is implemented currently ([here](https://github.com/Azure-Samples/active-directory-dotnet-webapi-onbehalfof/blob/master/TodoListService/Controllers/TodoListController.cs#L137)) (something I didn't realize until now).

So it seems that the sample was updated to work in a multi-user environment, but nothing prevents a developer from doing the same mistake as I did (following the original sample code) as long as there is a constructor for `UserAssertion` that takes only an assertion value.

**Comment by kpanwar** [comment] 2016-01-15 20:54
A username is required to add entry to the cache. Documentation needs to be more explicit about it this.

**Comment by rwwilden** [comment] 2016-01-21 10:03
This also seems to be the cause of a token cache error I'm experiencing:

    Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException:
        multiple_matching_tokens_detected:
        The cache contains multiple tokens satisfying the requirements. Call AcquireToken
        again providing more requirements (e.g. UserId)

What I see happening is two users (almost) simultaneously storing a token in the cache (from two different threads). The next attempt to retrieve a token from the cache throws the exception.

The only thing I can't explain is how two tokens that the cache should regard as similar (since no username is provided in the `UserAssertion`) can still end up in the cache. There seems to be a discrepancy between *write-to-cache* token equality and *read-from-cache* token equality?!

Here are the two tokens (`TokenCacheItem`) (anonymized) I log from the cache right before the exception occurs:

    user01@outlook.com                                        // DisplayableId
     | eyJ...                                                 // AccessToken
     | https://login.windows.net/mywebsite.onmicrosoft.com/   // Authority
     | a6d082b5-4d27-4d54-9f05-50138172ae3f                   // ClientId
     | 1/21/2016 9:01:50 AM +00:00                            // ExpiresOn
     | FamilyName01                                           // FamilyName
     | GivenName01                                            // GivenName
     | eyJ...                                                 // IdToken
     | live.com                                               // IdentityProvider
     | True                                                   // IsMultipleResourceRefreshToken
     | AAA...                                                 // RefreshToken
     | https://graph.windows.net                              // Resource
     | bcdc80d2-04b8-44c9-bf17-c62e857b00be                   // TenantId
     | b1a37305-8251-4ff3-9756-152ad6263dbf                   // UniqueId

    user02@gmail.com
     | <null>
     | https://login.windows.net/mywebsite.onmicrosoft.com/
     | a6d082b5-4d27-4d54-9f05-50138172ae3f
     | 1/20/2016 2:39:01 PM +00:00
     | FamilyName02
     | GivenName02
     | eyJ...
     | live.com
     | True
     | AAA...
     | https://graph.windows.net
     | bcdc80d2-04b8-44c9-bf17-c62e857b00be
     | e953264f-efe9-42f2-86a5-e64d16302712

As you can see both tokens have a `UniqueId`. So when writing the token to the cache they each receive a unique `UniqueId`. However, when reading the token, both `DisplayableId` and `UniqueId` are not considered.

**Comment by seriewe** [comment] 2016-01-26 11:21
I have the same problem like rwwilden described, and also hoped to fix the issue with the described solution. 
I use OpenIdConnectAuthentication and WindowsAzureActiveDirectoryBearerAuthentication in the same Project for the MVC App and an API. The API is called by a SP WebPart with a Token obtained by adal.js. Inside the Server Application I use the token to get a new token on behalf of the user and call some Office365 APIs.
In most cases the API works fine but sporadic I get the "multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements (e.g. UserId)" error.

My Problem is that I can’t reproduce the error. 
My AuthenticationContext use the Default in Memory Token Cache and I use the Microsoft.IdentityModel.Clients.ActiveDirectory Version 2.21.0.0

@rwwilden could you reproduce the error or did you find a fix?

I’t will be nice if somebody have a hint for me.

**Comment by rwwilden** [comment] 2016-01-26 12:22
Not been able to reproduce this yet. The problem occurs three to four times a week on a test environment. I added ADAL.NET as source code to the project and added additional logging in the library itself. Since then the problem hasn't come back yet... When anything happens I'll update this thread.

**Comment by kpanwar** [comment] 2016-02-27 03:17
@rwwilden - You should consider having cache per user in your server side implementation. Here is a post explaining it. http://www.cloudidentity.com/blog/2014/07/09/the-new-token-cache-in-adal-v2/

**Comment by kpanwar** [comment] 2016-04-11 04:08
We released fixed in both v2 and v3 where we also cache user assertion hash passed in and make sure that incorrect token is not returned for a given user.

**Comment by kpanwar** [comment] 2016-04-11 04:08
@seriewe Are you still running into issues?

**Comment by premchandpl** [comment] 2016-06-21 05:59
@kpanwar , I am facing this issue and this is the stack trace

System.AggregateException: One or more errors occurred. ---> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements (e.g. UserId)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadSingleItemFromCache(String authority, String resource, String clientId, TokenSubjectType subjectType, String uniqueId, String displayableId, CallState callState)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadFromCache(String authority, String resource, String clientId, TokenSubjectType subjectType, String uniqueId, String displayableId, CallState callState)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenOnBehalfCommonAsync>d__47.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.<GetAccessToken>d__11.MoveNext() in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Utility\\Authorization\\SPOAuthorization.cs:line 162\r\n   --- End of inner exception stack trace ---\r\n   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\r\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n   at System.Threading.Tasks.Task`1.get_Result()\r\n   at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.GetClientContext(String url) in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Utility\\Authorization\\SPOAuthorization.cs:line 93\r\n   at Microsoft.Legal.MatterCenter.Repository.Search.GetDocuments(SearchRequestVM searchRequestVM) in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Repository\\SharePointInfo\\Search.cs:line 232\r\n   at Microsoft.Legal.MatterCenter.Repository.DocumentRepository.<GetDocumentsAsync>d__8.MoveNext() in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Repository\\Document\\DocumentRepository.cs:line 61\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Web.Common.DocumentProvision.<GetDocumentsAsync>d__20.MoveNext() in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Web\\Common\\DocumentProvision.cs:line 375\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Web.DocumentController.<Get>d__11.MoveNext() in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Web\\Controllers\\DocumentController.cs:line 157\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.Mvc.Controllers.ControllerActionExecutor.<CastToObject>d__8`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.AspNet.Mvc.Controllers.ControllerActionInvoker.<InvokeActionAsync>d__6.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)\r\n   at Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeActionFilterAsync>d__53.MoveNext()\r\n---> (Inner Exception #0) Microsoft.IdentityModel.Clients.ActiveDirectory.AdalException: multiple_matching_tokens_detected: The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements (e.g. UserId)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadSingleItemFromCache(String authority, String resource, String clientId, TokenSubjectType subjectType, String uniqueId, String displayableId, CallState callState)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.TokenCache.LoadFromCache(String authority, String resource, String clientId, TokenSubjectType subjectType, String uniqueId, String displayableId, CallState callState)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__53.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenOnBehalfCommonAsync>d__47.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__32.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Legal.MatterCenter.Utility.SPOAuthorization.<GetAccessToken>d__11.MoveNext() in D:\\home\\site\\approot\\src\\Microsoft.Legal.MatterCenter.Utility\\Authorization\\SPOAuthorization.cs:line 162\n\tErrorCode: multiple_matching_tokens_detected<---\r\n

**Comment by kpanwar** [comment] 2016-07-25 08:00
Latest version of ADAL on both v2 and v3 support assertion hash matching now.

**Closed by kpanwar** 2016-07-25 08:00 UTC
