### ISSUE TITLE
Unable to Install ADAL using powershell.

### ISSUE THREAD

**Issue by mohitkhatri88** [AzureAD/azure-activedirectory-library-for-dotnet#1081] opened 2018-06-07 00:31 UTC
Hi All, 

I have been using [ADAL ](https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/)package for a Powershell script which i distribute to my customers. The powershell script is no longer able to install it as one of it's dependencies has been "unlisted" by it's owners. Can you please help me find a workaround to installing ADAL??

**I use the following command to install this library**
`Install-Package -Name "Microsoft.IdentityModel.Clients.ActiveDirectory" -Destination $Destination -ProviderName NuGet -Source 'https://www.nuget.org/api/v2' -ExcludeVersion -Force -ErrorAction Stop -ErrorVariable Installfailure`

**Error that i see when i run this command now:**
`Unable to find dependent package(s) (System.Reflection.Emit.Lightweight)`

**Package in question** : System.Reflection.Emit.Lightweight
This package has been "unlisted" by the owners as can be seen [here](https://www.nuget.org/packages/System.Reflection.Emit.Lightweight). Also, [this ](https://github.com/dotnet/corefx/issues/29365)discussion explains why the package was unlisted.

**Comment by jennyf19** [comment] 2018-06-07 16:42
@mohitkhatri88 Thanks for opening the issue. I was able to reproduce this. Will get back to you.

**Comment by bgavrilMS** [comment] 2018-06-07 21:56
Looks similar to this: https://github.com/PowerShell/PowerShell/issues/6988 - I'll try out their workaround and confirm.

**Comment by mohitkhatri88** [comment] 2018-06-07 22:37
Seems like the post is talking about `PSCoreWindowsCompat` as a replacement for `Microsoft.Windows.Compatibility` nuget package. Couldn't find ADAL as a component of [windows compatibility pack](https://blogs.msdn.microsoft.com/dotnet/2017/11/16/announcing-the-windows-compatibility-pack-for-net-core/).

Also, `PSCoreWindowsCompat` requires PowerShell 6, and I am working with Powershell 5 :(

**Comment by bgavrilMS** [comment] 2018-06-07 22:43
Yes, that workaround is for PowerShell Core (i.e. PS6), which lives side by side with PowerShell 5.

Here's my workaround, please try out - use the nuget CLI to install the package instead of Install-Package. Here's the PowerShell for it:

```
# Install the nuget command line (may have to do it for current user only to avoid admin prompt)
Find-Package -name NuGet.CommandLine -Source  'https://www.nuget.org/api/v2' | Install-Packa
ge

nuget install Microsoft.IdentityModel.Clients.ActiveDirectory
```

**Comment by bgavrilMS** [comment] 2018-06-07 22:44
Root cause issue seems to be https://github.com/OneGet/oneget/issues/322

**Comment by DamianWiese** [comment] 2018-06-07 23:07
Bogdan, I was able to use your workaround above to get the libraries downloaded from PowerShell. I tweaked your example a bit to drop them in a separate location since it doesn't look like nuget.exe gets added to the PATH variable automatically. 


`# Install the nuget command line (may have to do it for current user only to avoid admin prompt)
Find-Package -name NuGet.CommandLine -Source  'https://www.nuget.org/api/v2' | Install-Package
mkdir "C:\temp\ADALV3"
Set-Location "C:\temp\ADALV3"
Start-Process -FilePath "C:\Program Files\PackageManagement\NuGet\Packages\NuGet.CommandLine.4.6.2\tools\nuget.exe" -ArgumentList "install Microsoft.IdentityModel.Clients.ActiveDirectory"
`

**Comment by bgavrilMS** [comment] 2018-06-07 23:55
Closing the issue, please refer to OneGet/oneget#322 for the root cause, or use the workaround provided.

**Closed by bgavrilMS** 2018-06-07 23:55 UTC

**Comment by mohitkhatri88** [comment] 2018-06-08 00:42
The work around did it. Thanks @bgavrilMS @jennyf19
