### ISSUE TITLE
No support for SecureClientSecret for .NetStandard

### ISSUE THREAD

**Issue by rachelvwood** [AzureAD/azure-activedirectory-library-for-dotnet#1026] opened 2018-04-03 22:15 UTC
The [client credential flows wiki page](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows) says:
"On the .NET Framework 4.5 platform, the ISecureClientSecret interface is implemented by the SecureClientSecret class which can be built from a SecureString. However SecureString is not available on the other platforms, and therefore, on these platforms no implementation of the interface is provided"

SecureString is available out-of-the-box for NetStandard 2.0, and has been available as a [nuget package](https://www.nuget.org/packages/System.Security.SecureString/) for earlier versions of NetStandard.  Can we get the SecureClientSecret class for NetStandard?

**Comment by henrik-me** [comment] 2018-04-04 02:37
That should be possible to include in a future update. @jmprieur thoughts? @rachelvwood do you happen to have a PR with the change?

**Comment by jmprieur** [comment] 2018-04-04 14:28
That makes sense. The more similar the API is across platforms, the better, @henrik-me

**Comment by rachelvwood** [comment] 2018-04-05 22:32
I would be happy to make a PR for this, but I'm having problems building the project, and I've been trying for about a day now. "The reference assemblies for framework ".NETCore,Version=v4.5.1" were not found."  I have the latest netcore sdk, so I'm not sure what's wrong.

**Comment by jmprieur** [comment] 2018-04-06 14:27
@rachelvwood : did you read https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/build-and-test ?

**Comment by rachelvwood** [comment] 2018-04-06 15:46
Yep.  I have all requirements downloaded.

**Comment by jmprieur** [comment] 2018-04-06 15:49
@rachelvwood : thanks for checking. I'll try to setup a VM to understand the differences with our build configurations.
- which OS are you using?
- did you install VS 2015 and then VS 2017? (and which patch versions)?

**Comment by rachelvwood** [comment] 2018-04-06 16:12
Windows 10. Just VS 2017. 15.6.5

**Comment by jmprieur** [comment] 2018-04-06 17:04
I think you also need VS 2015 (and install it before VS 2017 which is a problem in your case), to be able to build it, as it requires WinRT.
Now, you could also build it with VSTS?

**Comment by rachelvwood** [comment] 2018-04-09 18:40
Uninstalled VS15, installed VS17.  Ran nuget restore.
ran "msbuild Combined.NoWinRT.sln /t:build /p:configuration=release"

Now I'm getting:
Platforms\winrt\CoreCryptographyHelpers.cs(64,24): error CS0012: The type 'IBuffer' is defined in an assembly that is
 not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToke
n=null, ContentType=WindowsRuntime'.

**Comment by jennyf19** [comment] 2018-04-09 20:12
@rachelvwood - You can try cleaning and rebuilding just Microsoft.Identity.Core and see if that helps (from Visual Studio 2017).
Also, can you see if building from the branch [adalv3/dev](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/tree/adalv3/dev) works for you?

**Comment by rachelvwood** [comment] 2018-04-09 20:31
@jennyf19 
I got the same errors for Microsoft.Identity.Core

adalv3/dev gave me errors during nuget restore:
error : Unable to load the service index for source https://msasg.pkgs.visualstudio.com/_packaging/Bing/nu
get/v3/index.json. [\azure-activedirectory-library-for-dotnet\ADAL.NET.NoWinRT.sln]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targe
ts(104,5): error :   Response status code does not indicate success: 401 (Unauthorized). [azure-activedir
ectory-library-for-dotnet\ADAL.NET.NoWinRT.sln]

**Comment by jennyf19** [comment] 2018-04-09 20:53
@rachelvwood - I'm not able to reproduce the errors you are seeing. I did some searching on-line, maybe try restarting Visual Studio. Also, make sure you have all the [required elements for building ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Visual-Studio-2017-Required-Components).

**Comment by henrik-me** [comment] 2018-11-02 18:25
@rachelvwood : Do you still find this to be important? Currently we do not target netstandard2. 

@bgavrilMS @MarkZuber @jmprieur @jennyf19 : I would suggest we support a target which includes netstandard2 (netcore2) and remove e.g. netcore1? That will enable us to get the support from the platform with-out additional packages?

**Comment by bgavrilMS** [comment] 2018-11-05 15:39
On ADAL we do not explicitly support netcore, we do it through netstandard. 
On MSAL, we explicitly support netcore 1.0+, and we already have a dependency on the SecureString package, so it would be trivial to expose the requested interface. I propose we do this for MSAL only.

**Comment by henrik-me** [comment] 2018-11-05 17:36
This would be for MSAL. Added feature request for MSAL: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/674.

Closing this issue.

**Closed by henrik-me** 2018-11-05 17:36 UTC
Labels: Enhancement
