### ISSUE TITLE
Issue on Xamarin.iOS after the password is reset for a user

### ISSUE THREAD

**Issue by mptolly** [AzureAD/azure-activedirectory-library-for-dotnet#508] opened 2016-07-29 15:26 UTC
I am seeing a UIKitThreadAccessException on Xamarin.iOS when executing the AuthenticationContext.AcquireTokenAsync(resource,clientId,returnUri,platformParameters) function after the user has changed their password. 

See StackTrace below:

```
2016-07-29 10:19:54.100 FactbookAppiOS[23624:1355584] 7/29/2016 3:19:54 PM: b82e4f57-3a80-4e2a-8057-b8c7a635491e - AdalHttpClient.cs: Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS70002: Error validating credentials. AADSTS70008: The refresh token has expired due to it being revoked. The token was issued on 2016-07-29T14:24:16.7404989Z and the TokensValidFrom date for this user is 2016-07-29T14:25:16.0000000Z. The user might have changed or reset their password.
Trace ID: 380797d9-f1fc-4327-86ac-0ac3ddef49e6
Correlation ID: b82e4f57-3a80-4e2a-8057-b8c7a635491e
Timestamp: 2016-07-29 15:19:53Z ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 400 (BadRequest).
  at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper+<GetResponseAsync>d__29.MoveNext () [0x0035d] in <filename unknown>:0 
  --- End of inner exception stack trace ---
	ErrorCode: invalid_grant
	StatusCode: 400
2016-07-29 10:19:54.108 FactbookAppiOS[23624:1355584] 7/29/2016 3:19:54 PM: b82e4f57-3a80-4e2a-8057-b8c7a635491e - AcquireTokenHandlerBase.cs: UIKit.UIKitThreadAccessException: UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread.
  at UIKit.UIApplication.EnsureUIThread () [0x00023] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/src/UIKit/UIApplication.cs:88 
  at UIKit.UIApplication.CanOpenUrl (Foundation.NSUrl url) [0x00000] in /Users/builder/data/lanes/3412/3cf8aaed/source/maccore/src/build/ios/native/UIKit/UIApplication.g.cs:188 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.BrokerHelper.get_CanInvokeBroker () [0x00023] in <filename unknown>:0 
  at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase+<RunAsync>d__55.MoveNext () [0x00394] in <filename unknown>:0 
```

I have found a workaround that let me handle the prompt as expected.  The code for the workaround is below:

```
try{
    AuthenticationContext.AcquireTokenAsync(resource,clientId,returnUri,platformParameters);
}
catch(UIKitThreadAccessException tae){
    AuthenticationContext.TokenCache.Clear();
    AuthenticationContext.AcquireTokenAsync(resource,clientId,returnUri,platformParameters);
}
```

**Comment by kpanwar** [comment] 2016-08-18 16:50
The issue is not with password update. The issue is that canOpenUrl() requires UIThread. What version of iOS are you running

**Comment by mptolly** [comment] 2016-08-18 16:57
I am running on the iOS 9.3.4 simulator.

**Comment by kpanwar** [comment] 2016-08-23 00:28
I am unable to repro your issue with an iOS app and XForms app. Can you share the exact code you are running?

**Comment by mptolly** [comment] 2016-08-23 00:37
I am running the code in a Xamarin.iOS app, no Xamarin.Forms.

I am running the following lines of code in the FinishedLaunching method of the AppDelegate.

ApiProperties.AuthenticationContext = new AuthenticationContext(ApiProperties.Authority);
            if (ApiProperties.AuthenticationContext.TokenCache.ReadItems().Count() > 0)
                ApiProperties.AuthenticationContext = new AuthenticationContext(ApiProperties.AuthenticationContext.TokenCache.ReadItems().First().Authority);

Then, in the ViewDidLoad of my RootViewController I run the following line:

AuthenticationResult authResult = await ApiProperties.AuthenticationContext.AcquireTokenAsync(ApiProperties.WebApiId, ApiProperties.ClientId, new Uri(ApiProperties.ReturnUrl), new PlatformParameters(this));

*NOTE: I marked ViewDidLoad as async

**Comment by kpanwar** [comment] 2016-08-23 00:40
FinishedLaunching of AppDelegate is fired before the view is actually loaded. the API call should be made in a your view controller's viewLoaded() instead.

**Comment by mptolly** [comment] 2016-08-23 00:47
I did not, as other than the crash after a password change, everything is working as expected.

**Comment by kpanwar** [comment] 2016-08-23 00:48
I just tried the same and I don't this problem. I see "2016-08-22 17:47:26.100 SimpleiOSApp[6482:77128] Warning: Attempt to present <AuthenticationAgentUINavigationController: 0x7c36d800> on <MainViewController: 0x7a71e610> whose view is not in the window hierarchy!"

One difference is that I created the auth context inside viewDidLoad

**Comment by mptolly** [comment] 2016-08-23 01:53
I moved the the code to the ViewDidLoad method and still got the error.  As I noted above, I have async on the ViewDidLoad method signature (public override async void ViewDidLoad(){}).  Could that be contributing to the error showing?

**Comment by kpanwar** [comment] 2016-08-23 01:57
you can test by adding a simple button and calling acquireToken in the Action implementation.

**Comment by kpanwar** [comment] 2016-08-23 20:12
What is the ADAL version you are using?

**Comment by mptolly** [comment] 2016-08-23 22:01
I am using 3.13.1.

**Comment by kpanwar** [comment] 2016-08-23 22:16
We already have 13.3.3 out. try that. Also please try to call acquireToken in a button click event

**Comment by mptolly** [comment] 2016-08-24 02:24
An error is still thrown in 3.13.3 (the latest version it allows me to update to), however this time I get an AdalException with the message "authentication_ui_failed" that is wrapped around the "UIKit Consistency error: you are calling a UIKit method that can only be invoked from the UI thread." exception.  Hooking up the authentication to a button when the app is opened from a closed state is not an option, as I need to query a Azure AD OAuth2 protected web service to see if data must be downloaded when the app opens.

**Comment by kpanwar** [comment] 2016-08-24 02:51
I have made the fix. pending release

**Comment by kpanwar** [comment] 2016-08-24 03:31
fixed in 3.13.4

**Closed by kpanwar** 2016-08-24 03:31 UTC

**Comment by bjartebore** [comment] 2016-12-02 09:03
This seems to still be a problem in 3.13.17 when brokered authentication is enabled

> at UIKit.UIApplication.EnsureUIThread () [0x00023] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/src/UIKit/UIApplication.cs:88 
at UIKit.UIApplication.CanOpenUrl (Foundation.NSUrl url) [0x00000] in /Users/builder/data/lanes/3969/44931ae8/source/xamarin-macios/src/build/ios/native/UIKit/UIApplication.g.cs:190 
at Microsoft.IdentityModel.Clients.ActiveDirectory.BrokerHelper.get_CanInvokeBroker () [0x00027] in /Users/bjarte.bore/Prosjekt/statoil/mad/azure-activedirectory-library-for-dotnet/src/ADAL.PCL.iOS/BrokerHelper.cs:52 
at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase+<RunAsync>c__async0.MoveNext () [0x00383] in /Users/bjarte.bore/Prosjekt/statoil/mad/azure-activedirectory-library-for-dotnet/src/ADAL.PCL/AcquireTokenHandlerBase.cs:152 
--- End of stack trace from previous location where exception was thrown ---

**Comment by delaney31** [comment] 2017-05-26 14:52
Thank you for your workaround. I'm having the exact same issue!
