### ISSUE TITLE
CreateAuthenticationDialog - The method or operation is not implemented.

### ISSUE THREAD

**Issue by markdwags** [AzureAD/azure-activedirectory-library-for-dotnet#879] opened 2017-10-25 16:42 UTC
I'm attempting to acquire a token from ADFS 3.0 using OAuth2 using .NET Core.  Using .NET 4.5, I have no issues because of a combination of PromptBehavior.Never and it automatically handling in the passing in the credentials of the Windows user who is logged in.

In .NET Core, that isn't available (long term this will run from an AWS Lambda function) but I'm unable to find a way to package in the username/password that has permission to auth to get the token to put into the Authorization header in the HttpClient in a way that works with CRM 2016.

ADFS 3.0 OAuth2 with the ADFS Client is very specific, and requires that you pass in a resource (which is the ADFS defined URL), the client ID (created on the ADFS server with Add-AdfsClient), and the redirect URL (also defined using Add-AdfsClient).  

```
string resource = "https://site.url.com/";
string clientId = "11111111-1111-1111-1111-11111111111";
string redirectUrl = "https://site.url.com/CRM/";

AuthenticationContext authContext = new AuthenticationContext("https://adfs.domain.com/adfs/oauth2", false);

var platformParams = new PlatformParameters();

var authResult = await authContext.AcquireTokenAsync(resource, clientId, new Uri(redirectUrl), platformParams);
```

It's kicking out this error.

```
{System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.IdentityModel.Clients.ActiveDirectory.WebUIFactory.CreateAuthenticationDialog(IPlatformParameters parameters) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenCommonAsync>d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CRMTestCore.Program.<TestNewTokenWay>d__2.MoveNext() in C:\Projects\CRMTestCore\CRMTestCore\CRMTestCore\Program.cs:line 140}	System.Exception {System.NotImplementedException}

```

Essentially, I need a way to bypass this auth dialog and input my own domain, username and password that it will use to authenticate to get the token.

Thanks!

**Comment by kpanwar** [comment] 2017-10-25 16:49
We don’t support username password based flows in .net core. But at the same time adfs v3 does not support username password based authentication (resource owner flow) either.

**Comment by markdwags** [comment] 2017-10-25 17:02
Regarding username/password, I was referring to this flow. 

For example, on Windows using .NET 4.5, the following code will use the credentials of the logged in user automatically.

```
string resource = "https://site.url.com/";
string clientId = "11111111-1111-1111-1111-11111111111";
string redirectUrl = "https://site.url.com/CRM/";

AuthenticationContext authContext = new AuthenticationContext("https://adfs.domain.com/adfs/oauth2", false);

AuthenticationResult authResult = authContext.AcquireToken(resource, clientId, new Uri(redirectUrl), PromptBehavior.Never);
```

If I were to use `PromptBehavior.Always` for example, I get the dialog prompt where I can enter any domain credentials for ADFS to use to authenticate against AD and assuming authentication is successful, authRequest has a token I can use for the HttpClient.

I'm able to package in domain credentials using the HttpClientHandler in .NET Core (so I have the ability to run in Linux) 

```
 HttpClientHandler _httpClientHandler = new HttpClientHandler()
{
        Credentials = new NetworkCredential("aduser", "adpassword", "domain.tld"),                  
};
```

I was inquiring (and hoping!) this library would support something similar.

**Comment by angshuman-agarwal** [comment] 2018-04-16 10:56
```
string resource = "https://site.url.com/";
string clientId = "11111111-1111-1111-1111-11111111111";
string redirectUrl = "https://site.url.com/CRM/";

AuthenticationContext authContext = new AuthenticationContext("https://adfs.domain.com/adfs/oauth2", false);

AuthenticationResult authResult = authContext.AcquireToken(resource, clientId, new Uri(redirectUrl), PromptBehavior.Never);
```

I do not believe above will work with `PromptBehavior.Never` because the very 1st time , it token is not present in cache, it will flash up a web browser and `PromptBehavior.Never` will fail.

Please read `Note that:` section [here ](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-tokens-interactively---Public-client-application-flows#properties-or-platformparameters-constructors-parameters-common-to-most-platforms) which says :
 
_If you use PromptBehavior = Never and the token does not exist in the cache, or needs to be refreshed with UI, the call to AcquireTokenAsync will fail with an exception of type AdalException_

**Comment by jmprieur** [comment] 2018-04-16 14:03
markdwags, the flow you describe above is an interactive flow which is not supported in .NET core as .NET core does not offer a Web browser 

Indeed @angshuman-agarwal, indeed one should what is described in [recommended pattern to acquire a token in public client application](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token). you should first try the cache, and if this fail you try the interaction.

Also see this summary for which platform supports which flow: [summary for public client applications](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Acquiring-a-token-return-AuthenticationResult-and-possibly-UserInfo#summary-for-public-client-applications)

__
closing this issue as by design as .NET Core does not support UI yet. We will implement interactive flows in .NET Core when it does.

**Closed by jmprieur** 2018-04-16 14:03 UTC
Labels: By Design

**Comment by jmprieur** [comment] 2018-04-16 15:08
@angshuman-agarwal  if you use systematically AcuireTokenSilentAsync before your call to AcquireTokenAsync( with Auto), then you will not see any browser.

**Comment by angshuman-agarwal** [comment] 2018-04-16 15:39
@jmprieur 

Sorry, that is not true. 

I followed this [pattern here](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-a-cached-token#recommended-pattern-to-acquire-a-token) where I call `AcuireTokenSilentAsync` 1st and then in `catch`  I *will have* to call `AcquireTokenAsyc` as very `1st time`, token will not be found silently and always requires Interaction.

**Comment by jmprieur** [comment] 2018-04-16 15:46
@angshuman-agarwal. I'm confused about what you want to achieve

This is an interactive flow. so the very first time the user uses the application, s/he will have to sign-in interactively. Then,  provided you have implemented a [token cache serialization](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Token-cache-serialization) (only needed on .NET Framework and .NET Core), you won't have to re-sign in the user.

Now, if you are in an enterprise scenario, with the user's machine domain or AAD joint, you'd want to use the [Windows integrated authentication flow](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/AcquireTokenSilentAsync-using-Integrated-authentication-on-Windows-(Kerberos)), which does not show a browser (but that was not my understanding from the thread above. Sorry if I missed something)

**Comment by markdwags** [comment] 2018-04-16 15:52
@jmprieur 

I'm trying to get past the part that requires someone to sign in interactively -- where it would use an Active Directory username and password (stored in a config or obtained some other way) that I pass in instead to bypass the interactive window.

Specifically, my use-case is attempting to get this token from an AWS Lambda function and then using that token to interact with the CRM Web API with that token.

Unfortunately, my "work around" has been to have a Windows Service installed that gets that token every minute, then pushes the value to AWS Lambda so the function can use the token.  I'd love to not have this extra service, instead allow the Lambda function to obtain this token.

**Comment by angshuman-agarwal** [comment] 2018-04-16 17:27
I will open a new issue. Sorry about that
