### ISSUE TITLE
AcquireTokenAsync throws CryptographicException: Key not valid for use in specified state.

### ISSUE THREAD

**Issue by GitHubSachin** [AzureAD/azure-activedirectory-library-for-dotnet#1083] opened 2018-06-08 04:55 UTC
We are getting following exception when using c# library calling AcquireTokenAsync method.
Is there any fix for this, we verified certificate on the machine is correct installed, user account running have access to its private key and can use it via certutil.exe

---> System.Security.Cryptography.CryptographicException: Key not valid for use in specified state.
 
   at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
   at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
   at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
   at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
   at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
   at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm, Boolean privateKey)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate.Sign(String message)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.JsonWebToken.Sign(IClientAssertionCertificate credential)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.ClientKey.AddToParameters(IDictionary`2 parameters)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AcquireTokenHandlerBase.<RunAsync>d__55.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__27.MoveNext()

**Comment by henrik-me** [comment] 2018-06-11 19:30
@GitHubSachin Do you have a repro steps and more details on the cert you are using? I may not understand the stack trace entirely but it's eluding at the private key not being available in the cert?

**Comment by brentschmaltz** [comment] 2018-06-11 20:33
@GitHubSachin Can you add what .Net Target you app specifies and what .Net version is on the test machine?

**Comment by jmprieur** [comment] 2018-06-14 08:42
@GitHubSachin : 
I got a similar experience when copying to a different machine, the folder structure of a sample that serializes the token cache in a file protected with [ProtectedData.Protect](https://msdn.microsoft.com/en-us/library/2fh8203k(v=vs.110).aspx)

That's the case, for instance when using the `FileCache` class that we provide in our .NET Desktop client samples (.NET Framework and .NET Core). The line is here:
https://github.com/Azure-Samples/active-directory-dotnet-native-desktop/blob/master/TodoListClient/FileCache.cs#L78

Would you be in this case? If this is your case, the recommendation is to delete the file containing the serialized cache

**Comment by GitHubSachin** [comment] 2018-06-14 20:21
@brentschmaltz We compile our app with .net 4.5.2 (desktop version)
I don't have exact repro steps but this gets reported in production by one of our app users and not consistently repro. If I hear any detailed from user, I will post it here.

**Comment by brentschmaltz** [comment] 2018-07-03 17:01
@jmprieur I am not seeing DPAPI in this stack.

@GitHubSachin X509AsymmetricSecurityKey.GetAsymmetricAlgorithm sometimes has issues with SHA2 or when .Net is upgraded to 4.6+.
What version of ADAL are you using?

**Comment by GitHubSachin** [comment] 2018-07-06 18:05
We use 3.19.4 version of ADAL, the app is compiled with .net 4.5.2 desktop version.

**Comment by henrik-me** [comment] 2018-07-06 22:42
@GitHubSachin - a few additional questions
What OS is the service running on and which version of .net is on that box? 
How frequent does this issue occur? 
Has the server been restarted?

**Comment by Eldar1205** [comment] 2018-08-19 16:48
Hi,

We also experience the same issue, and it's not consistent across our machines.
We use .Net Framework 4.7.2, ADAL version 3.19.8, and in local workstations this method call works for us and on our test agents it doesn't, for the same certificate. When the same code is compiled using .Net 4.5.2 with same certificate it works correctly on our test agent, so the regression is related somehow to the different in .Net framework. The issue is deterministic, happens every time we run test agents, and never happens when we execute from local workstations.

Our callstack looks different from above, I assume due to changes in ADAL from 3.19.4 to 3.19.8:

at System.Security.Cryptography.Utils.CreateProvHandle(CspParameters parameters, Boolean randomKeyContainer)
at System.Security.Cryptography.Utils.GetKeyPairHelper(CspAlgorithmType keyType, CspParameters parameters, Boolean randomKeyContainer, Int32 dwKeySize, SafeProvHandle& safeProvHandle, SafeKeyHandle& safeKeyHandle)
at System.Security.Cryptography.RSACryptoServiceProvider.GetKeyPair()
at System.Security.Cryptography.RSACryptoServiceProvider..ctor(Int32 dwKeySize, CspParameters parameters, Boolean useDefaultKeySize)
at System.Security.Cryptography.X509Certificates.X509Certificate2.get_PrivateKey()
at System.Security.Cryptography.X509Certificates.RSACertificateExtensions.GetRSAPrivateKey(X509Certificate2 certificate)
at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.get_PrivateKey()
at System.IdentityModel.Tokens.X509AsymmetricSecurityKey.GetAsymmetricAlgorithm(String algorithm, Boolean privateKey)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Platform.CryptographyHelper.SignWithCertificate(String message, X509Certificate2 certificate)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.JsonWebToken.Sign(IClientAssertionCertificate credential, Boolean sendX5C)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.ClientCreds.ClientKey.AddToParameters(IDictionary`2 parameters)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<SendTokenRequestAsync>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<CheckAndAcquireTokenUsingBrokerAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Flows.AcquireTokenHandlerBase.<RunAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenForClientCommonAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.<AcquireTokenAsync>d__58.MoveNext()

**Comment by henrik-me** [comment] 2018-08-20 03:41
@brentschmaltz : Would like to get your perspective on this one.

**Comment by brentschmaltz** [comment] 2018-08-23 17:19
@Eldar1205 can you share the code you make to call adal?

**Comment by Eldar1205** [comment] 2018-08-23 17:36
I can't reveal the details of specific parameters, but this is the overall  code structure:

```
string certificateThumbprint = ...
string resource = ...
tring clientId = ...
string authority = ...
X509Certificate2 certificate = GetCertificate(certificateThumbprint);
var assertionCertificate = new ClientAssertionCertificate(clientId, certificate);
var authContext = new AuthenticationContext(authority, TokenCache.DefaultShared);
await authContext.AcquireTokenAsync(resource, assertionCertificate);
```
The method _GetCertificate_ looks for a certificate with given thumbprint in either CurrentUser/My or LocalMachine/My using the code below:

`
public static X509Certificate2 FindCertificateByThumbprint(string thumbprint, StoreLocation storeLocation = StoreLocation.CurrentUser, bool trace = false)
        {
            var store = new X509Store(StoreName.My, storeLocation);
            try
            {
                store.Open(OpenFlags.ReadOnly);
                var certs = store.Certificates.Find(X509FindType.FindByThumbprint, thumbprint, false);
                if (certs == null || certs.Count == 0)
                {
                    if (trace)
                    {
                        Tracer.Information($"Can't find cert '{thumbprint}' in {store.Name}/{store.Location}.");
                    }

                    return null;
                }

                if (trace)
                {
                    Tracer.Information($"Found cert '{thumbprint}' in {store.Name}/{store.Location}. HasPrivateKey: {certs[0].HasPrivateKey}");
                }

                return certs[0];
            }
            finally
            {
                store.Close();
            }
        }`

Does this help or more details are needed?

**Comment by Eldar1205** [comment] 2018-08-27 19:24
@brentschmaltz  Friendly ping :)

**Comment by brentschmaltz** [comment] 2018-08-28 16:48
@Eldar1205 I'll have to dig through the code. In the meantime, can you tell me about the Certificate? Is it signed with SHA2? Any extensions? Did you set a 'quirk' to turn off CNG?   

```
<runtime>
    <AppContextSwitchOverrides value="Switch.System.IdentityModel.DisableCngCertificates=true" />
</runtime>
```

**Comment by Eldar1205** [comment] 2018-08-28 17:33
Signed with Sha2, CNG is default mode no quirks. What do you mean by
extensions?

**Comment by henrik-me** [comment] 2019-06-28 22:24
Closing as we are not adding new features to ADAL. If you believe there is an issue which needs to be addressed in ADAL, please don't hesitate to re-open or create a new issue.

Please try out [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet), the authn library which is part of the Microsoft identity platform.

If you find any issues using MSAL, please open an issue there.

**Closed by henrik-me** 2019-06-28 22:24 UTC
