### ISSUE TITLE
Platform Parameters is not accepting any parameter for android with latest version of the ADAL

### ISSUE THREAD

**Issue by RamanathanC** [AzureAD/azure-activedirectory-library-for-dotnet#949] opened 2018-01-19 13:22 UTC

**Comment by jmprieur** [comment] 2018-01-19 15:14
@RamanathanC : can you please provide repro steps ? (or repro code)?

**Comment by reutann** [comment] 2018-01-23 16:27
@RamanathanC, I was running into this as well - you need to change the lib type in your .csproj to monoandroid7 

![image](https://user-images.githubusercontent.com/25594617/35287441-55d74f3c-0030-11e8-9009-a8cb636761c2.png)

**Comment by jmprieur** [comment] 2018-01-23 17:39
@RamanathanC 
Do you mean that when added the NuGet package the reference in your Xamarin.Android project was wrong?

**Comment by jmprieur** [comment] 2018-02-13 11:38
Closing as by design, as ADAL.NET needs to be reference by the right type of project (if needed use multiple target frameworks)

**Closed** 2018-02-13 11:37 UTC
